# Generated by Django 3.2.8 on 2021-10-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_entry_tidiness_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.PositiveIntegerField(choices=[(5, 'really good'), (4, 'good'), (3, 'neutral'), (2, 'bad'), (1, 'really bad')]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tidiness_rating',
            field=models.PositiveIntegerField(choices=[(5, 'really tidy'), (4, 'tidy'), (3, 'neutral'), (2, 'untidy'), (1, 'really untidy')]),
        ),
    ]
